apiVersion: ray.io/v1
kind: RayService
metadata:
  name: vllm
spec:
  serveConfigV2: |
    applications:
    - name: tiny-llama
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        max_ongoing_requests: 2
        autoscaling_config:
          target_ongoing_requests: 1
          min_replicas: 1
          max_replicas: 9
        ray_actor_options:
          num_cpus: 4
          # NOTE: num_gpus is set automatically based on TENSOR_PARALLELISM
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        pip: ["vllm==0.5.4"]
        env_vars:
          MODEL_ID: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
          TENSOR_PARALLELISM: "1"
          PIPELINE_PARALLELISM: "1"
  rayClusterConfig:
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
        num-cpus: "0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray-ml:2.33.0.914af0-py311
              resources:
                limits:
                  cpu: "2"
                  memory: "8Gi"
                requests:
                  cpu: "2"
                  memory: "8Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 7
        groupName: tiny-llama-pack
        rayStartParams: {}
        template:
          spec:
            runtimeClassName: nvidia
            containers:
              - name: tiny-llama
                image: rayproject/ray-ml:2.33.0.914af0-py311
                resources:
                  limits:
                    cpu: "8"
                    memory: "10Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "8"
                    memory: "10Gi"
                    nvidia.com/gpu: "1"
