apiVersion: ray.io/v1
kind: RayService
metadata:
  name: hermes-2-pro
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 8
          # NOTE: num_gpus is set automatically based on TENSOR_PARALLELISM
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        pip: ["vllm==0.4.3"]
        env_vars:
          MODEL_ID: "defenseunicorns/Hermes-2-Pro-Mistral-7B-4bit-32g-GPTQ"
          TENSOR_PARALLELISM: "1"
          PIPELINE_PARALLELISM: "1"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray-ml:2.33.0.914af0-py311
              resources:
                limits:
                  cpu: "2"
                  memory: "8Gi"
                requests:
                  cpu: "2"
                  memory: "8Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: gpu-group
        rayStartParams: {}
        template:
          spec:
            runtimeClassName: nvidia
            containers:
              - name: llm
                image: rayproject/ray-ml:2.33.0.914af0-py311
                resources:
                  limits:
                    cpu: "8"
                    memory: "10Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "8"
                    memory: "10Gi"
                    nvidia.com/gpu: "1"
