apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: hf-mistral
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=mistral
        - --model_id=justinthelaw/Hermes-2-Pro-Mistral-7B-4bit-32g
      resources:
        limits:
          cpu: "6"
          memory: 24Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "6"
          memory: 24Gi
          nvidia.com/gpu: "1"
